services:
  postgres:
    image: postgres:17
    container_name: postgres_db
    restart: always
    env_file:
      - ./apps/backend/.env
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 0406
      POSTGRES_DB: feed
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: apps/backend
    container_name: backend
    depends_on:
      - postgres
    env_file:
      - ./apps/backend/.env
    ports:
      - "3000:3000"
    volumes:
      - ./apps/backend:/app
      - /app/node_modules

  frontend:
    build:
      context: apps/frontend
    container_name: frontend
    depends_on:
      - backend
    env_file:
      - ./apps/frontend/.env
    ports:
      - "5173:5173"
    volumes:
      - ./apps/frontend:/app
      - /app/node_modules

volumes:
  postgres_data: